Rewriting enumerable methods
Jmagero/Enumerable-methods pull request #1
Opened 2020-06-02 20:13 UTC by Jmagero

In this project I have  implemented my own version of Ruby's Enumerables, which include each, each_with_index. any?, all?, none? count, map and inject.

2020-06-04 05:56 UTC, MarioDena requested changes
Hello! Good job on your project however there are some changes that need to be made. :smiley: 

## Changes required 

- [ ] my_each should returns the array itself when a block is given after calling the given block once for each element in self. Please implement this on your method
- [ ] my_each_with_index Same as above.
- [ ] my_none? method is missing please implement it
- [ ] my_count should counts the number of items in enum that are equal to item if an argument is given, please implement this functionality
- [ ] my_map method is missing please implement it
- [ ] my_inject should, when a symbol is specified combines each element of the collection by applying the symbol as a named method.
- [ ] There is something wrong with your stickler set-up and no linter test are shown on your PR. please fix this.

After making the requested changes please re-submit your code for review! Cheers! :+1:

2020-06-04 18:48 UTC, Jmagero commented
### TSE required changes fixed

-  my_each should returns the array itself when a block is given after calling the given block once for each element in self. Please implement this on your method
- my_each_with_index Same as above.
- my_none? method is missing please implement it
- my_count should counts the number of items in enum that are equal to item if an argument is given, please implement this functionality
- my_map method is missing please implement it
- my_inject should, when a symbol is specified combines each element of the collection by applying the symbol as a named method.
- There is something wrong with your stickler set-up and no linter test are shown on your PR. please fix this.

2020-06-05 13:50 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi there @Jmagero 
Great working on the requested changes. However, there still some methods that we need to improve. The reason for this is because in this assignment your methods should work very similar to the original ones. **Check my comments bellow**

Please kindly submit for code review again after making these changes.
Happy coding
**Sergio Torres**

2020-06-05 13:50 UTC, Torres-ssf commented on main.rb
> +  end
- [ ] my_each when a block is given when self is a range after calling the given block once for each element in self, returns the range itself. Your method is returning an array, even when calling my_each from a range

Example:
`(1..3).my_each { | value | puts value }` should print 1, 2 and 3, and after that should return the range itself `1..3`

Print from the original method:

![Screenshot from 2020-06-05 09-19-36](https://user-images.githubusercontent.com/30977845/83875559-b1f10e80-a70d-11ea-9870-7af5abdfb004.png)

2020-06-05 13:50 UTC, Torres-ssf commented on main.rb
> +  end
- [ ] my_each_with_index when a block is given when self is a range after calling the given block once for each element in self, returns the range itself. Your method is returning an array, even when calling my_each_with_index from a range

Example:
`(1..3).my_each_with_index { | value, index | puts index }` should print 0, 1 and 2, and after that should return the range itself `1..3`

Print from the original method:

![Screenshot from 2020-06-05 09-22-33](https://user-images.githubusercontent.com/30977845/83875778-1a3ff000-a70e-11ea-9d1a-d2d00353a787.png)

2020-06-05 13:50 UTC, Torres-ssf commented on main.rb
> +  end
- [ ] my_all? when a class is passed as an argument returns true if all of the collection is a member of such Class. 
Example:

`[1, 2.14, 0.5, 0].my_all?(Numeric)` should return true
`[1, 2.14, 0.5, 0].my_all?(Integer)` should return false
`[1, 2.14, 0.5, 'hello'].my_all?(String)` should return false

2020-06-05 13:50 UTC, Torres-ssf commented on main.rb
> +  end
- [ ] my_any? returns false if the block ever returns a value false or nil. This method is working OK for an array, but it throws an error when calling it from a range.

Example:

`(1..10).my_any? { | value | value > 10 }` should return false
`(1..11).my_any? { | value | value > 10 }` should return true

Print from the original method:
![Screenshot from 2020-06-05 09-44-27](https://user-images.githubusercontent.com/30977845/83877606-3002e480-a711-11ea-98f8-cc384561c6c0.png)


- [ ] my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class.

`[1, 2.14, 0.5, 0].my_any?(Integer)` should return true
`[2.14, 0.5].my_any?(Integer)` should return false
`[1, 2.14, 0.5, 'hello'].my_any?(String)` should return true

2020-06-05 13:50 UTC, Torres-ssf commented on main.rb
> +  end
- [ ] my_none? returns false if the block ever returns true for all elements. This method is working OK for an array, but it throws an error when calling it from a range.

Example:

`(1..10).my_none? { | value | value > 11 }` should return true
`(1..10).my_none? { | value | value > 9 }` should return false

Print from the original method:
![Screenshot from 2020-06-05 09-52-04](https://user-images.githubusercontent.com/30977845/83878258-3f366200-a712-11ea-8729-065ebfba12fd.png)

2020-06-05 13:50 UTC, Torres-ssf commented on main.rb
> +  end
- [ ] my_count returns the number of items in enum through enumeration. This method is working OK for an array, but it throws an error when calling it from a range.

`(1..10).my_count` should return 10

Print from the original method:
![Screenshot from 2020-06-05 09-57-19](https://user-images.githubusercontent.com/30977845/83878738-faf79180-a712-11ea-9c58-0a5538aad1e7.png)

2020-06-05 13:50 UTC, Torres-ssf commented on main.rb
> +  end
- [ ] my_inject raises a "LocalJumpError" when no block or argument is given

Example:

`[1, 2, 3, 4, 5].inject` should raise a LocalJumpError

Print original method:
![Screenshot from 2020-06-05 10-02-24](https://user-images.githubusercontent.com/30977845/83879242-b5879400-a713-11ea-9443-4fac8b0ac675.png)

- [ ] my_inject, when a block is given without an initial value, combines all elements of enum by applying a binary operation, specified by a block

Example: 

`[1, 2, 3, 4, 5].my_inject { |sum, value| sum + value }` should return 15
`[1, 2, 3, 4, 5].my_inject { |product, value| product * value }` should return 120
`[1, 2, 3, 4, 5].my_inject { |sub, value| sub - value }` should return 13

Should also work for Range:

`(1..5).inject { |sum, value| sum + value }` should return 15

2020-06-09 18:04 UTC, Jmagero commented
### Fixed these errors
-  my_each when a block is given when self is a range after calling the given block once for each element in self, returns the range itself.
- my_each_with_index when a block is given when self is a range after calling the given block once for each element in self, returns the range itself. 
- my_all? when a class is passed as an argument returns true if all of the collection is a member of such Class.
- my_any? returns false if the block ever returns a value false or nil. This method is working OK for an array, but it throws an error when calling it from a range.
- my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class.
- my_none? returns false if the block ever returns true for all elements. This method is working OK for an array, but it throws an error when calling it from a range.
- my_count returns the number of items in enum through enumeration. This method is working OK for an array, but it throws an error when calling it from a range.
- my_inject raises a "LocalJumpError" when no block or argument is given

2020-06-09 22:41 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @Jmagero :balloon: 

### Thank you for doing the changes requested by the previous reviewers :medal_sports: your project is working better and better every time, :muscle: please address to the changes I've left in your code :point_down: 

### That's it! :raised_hands: 

### Please :pray:  do the changes :woman_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-06-09 22:41 UTC, euqueme commented on README.md
> +# project-bubble-sort
- [ ] The project is called Enumerable-methods not bubble-sort let's correct it

2020-06-09 22:41 UTC, euqueme commented on main.rb
> +  end
- [ ] should have working `my_any?` identical and returns the same thing as ruby's [`any?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

-  When no block or argument is given returns false if at least one of the collection is not true
```ruby
[false, false, nil].my_any? == [false, false, nil].any? # => false
```
Yours (wrong answer)
![image](https://user-images.githubusercontent.com/52209067/84203069-0b3aa400-aa66-11ea-82d0-13c52ab4b373.png)

Real any? (correct)
![image](https://user-images.githubusercontent.com/52209067/84203096-18f02980-aa66-11ea-87a5-41d7f3512340.png)

- When a class is passed as an argument returns true if at least one of the collection is a member of such class::Integer

```Ruby
['1', '2', '5', false].my_any?(Integer) == ['1', '2', '5', false].any?(Integer) # => false
```
Yours (wrong answer)
![image](https://user-images.githubusercontent.com/52209067/84203398-9b78e900-aa66-11ea-86af-7621d1684ff3.png)

Real any? (correct)
![image](https://user-images.githubusercontent.com/52209067/84203430-a7fd4180-aa66-11ea-87bb-f9b8154a0864.png)

- when a Regex is passed as an argument returns false if none of the collection matches the Regex

```ruby
['lorem','ipsum', 'dolo'].my_any?(/z/) == ['lorem','ipsum', 'dolo'].any?(/z/) # => false
```
Yours (wrong answer)
![image](https://user-images.githubusercontent.com/52209067/84204069-ca438f00-aa67-11ea-9af8-a69880613a4f.png)

Real any? (correct)
![image](https://user-images.githubusercontent.com/52209067/84204098-d6c7e780-aa67-11ea-8cd9-195e96ae927b.png)

- When a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
```ruby
['lorem','ipsum', 'dolo'].my_any?('cat') == ['lorem','ipsum', 'dolo'].any?('cat') # => false
```
Yours (wrong answer)
![image](https://user-images.githubusercontent.com/52209067/84205873-45f30b00-aa6b-11ea-868b-712204c11d1d.png)

Real any? (correct)
![image](https://user-images.githubusercontent.com/52209067/84205896-51decd00-aa6b-11ea-974a-63e639f3b869.png)

2020-06-09 22:41 UTC, euqueme commented on main.rb
> +  end
- [ ] should have working `my_inject` identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

- raises a "LocalJumpError" when no block or argument is given
```ruby
[1, 5, 8, 10].my_inject == [1, 5, 8, 10].inject 
```
Yours (incorrect)
![image](https://user-images.githubusercontent.com/52209067/84206570-a9ca0380-aa6c-11ea-9400-0148ca946895.png)

Real inject (correct)
![image](https://user-images.githubusercontent.com/52209067/84206610-bcdcd380-aa6c-11ea-9186-f9111c66d315.png)

- It searches for the element that meets the condition within a proc given as an argument

```ruby
search = proc { |memo, word| memo.length > word.length ? memo : word }
['lorem','ipsum', 'dolo'].my_inject(&search) == ['lorem','ipsum', 'dolo'].inject(&search) # => "ipsum"
```
Yours (incorrect)
![image](https://user-images.githubusercontent.com/52209067/84207160-ed713d00-aa6d-11ea-9354-9327c723c261.png)

Real inject (correct)
![image](https://user-images.githubusercontent.com/52209067/84207176-f95cff00-aa6d-11ea-9353-91b0ae06519c.png)

- when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block

```ruby
operation = proc { |sum, n| sum + n } 
[5, 10, 15, 20].my_inject(&operation) == [5, 10, 15, 20].inject(&operation) # => 50
```
Yours (Incorrect)
![image](https://user-images.githubusercontent.com/52209067/84207636-0fb78a80-aa6f-11ea-8ce6-94db6dbd6fe1.png)

Real inject (correct)
![image](https://user-images.githubusercontent.com/52209067/84207653-1a721f80-aa6f-11ea-858c-ddd7631de949.png)

- when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block::Range

```ruby
(1..10).my_inject { |prod, n| prod * n } == (1..10).my_inject { |prod, n| prod * n } # => 3628800
```
Yours (Incorrect)
![image](https://user-images.githubusercontent.com/52209067/84207820-7ccb2000-aa6f-11ea-89d5-6e133ada0a06.png)

Real inject (correct)
![image](https://user-images.githubusercontent.com/52209067/84207842-894f7880-aa6f-11ea-9741-6fa1e1e9b8f1.png)

2020-06-09 23:08 UTC, Jmagero commented
-  The project is called Enumerable-methods not bubble-sort let's correct it -Fixed

2020-06-10 03:40 UTC, kobiyoyo requested changes
## Hi @Jmagero        ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General

- [ ] `my_any?`:
- when no block or argument is given returns true if at least one of the collection is not false or nil
`p [nil, false, nil, false].my_any?` - should return `false`
- when a class is passed as an argument returns true if at least one of the collection is a member of such class
`p [12,3,34].my_any?(String)` should return `false`
- when a Regex is passed as an argument returns false if none of the collection matches the Regex
`p ['ghetto','wild'].my_any?(/z/)` should return `false`
- when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
`p ['cat',2,32,].my_any?('at')` should return `false`
- [ ] `my_inject`:
- When a symbol is specified combines each element of the collection by applying the symbol as a named method
`p (5..10).my_inject(2, :*) - should return 302400`
- Combines all elements of enum by applying a binary operation, specified by a block:
 `p (1..5).my_inject(4) { |prod, n| prod * n }` should return 480

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-06-10 10:45 UTC, Jmagero commented
### Fixed
- my_any?:
when no block or argument is given returns true if at least one of the collection is not false or nil
p [nil, false, nil, false].my_any? - should return false
when a class is passed as an argument returns true if at least one of the collection is a member of such class
p [12,3,34].my_any?(String) should return false
when a Regex is passed as an argument returns false if none of the collection matches the Regex
p ['ghetto','wild'].my_any?(/z/) should return false
when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
p ['cat',2,32,].my_any?('at') should return false
- my_inject:
When a symbol is specified combines each element of the collection by applying the symbol as a named method
p (5..10).my_inject(2, :*) - should return 302400
Combines all elements of enum by applying a binary operation, specified by a block:
p (1..5).my_inject(4) { |prod, n| prod * n } should return 480

2020-06-10 12:25 UTC, Torres-ssf approved these changes
### Project Approved :clap: :clap: :clap: 
Hi there @Jmagero 
Great work on this project :+1: 
I'm approving this PR :smile: 

**Only one thing to comment though, the `multiply_els` should not belong to the Enumerable module. So you can just remove it from the module and place below it.**

Good luck in the next Project

Happy coding :computer: 
**Sergio Torres**

2020-06-10 12:37 UTC, merged